### ISSUE TITLE
Investigate use of models

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/swift-client#5]
Investigate the usability of returning models instead of `Dictionary<String, Any>` from the API requests. Focus should be on v2 first, as those endpoints return structured responses

**Comment by sleepdefic1t** [comment]
Two things we discovered while working on Cpp that are potentially worth noting:

In order to properly validate most models,
crypto functions must be used;
which would necessitate using the crypto lib.

Brian had also expressed a preference towards allowing the dev to decide how the response data is handled.

Given those two points combined with the memory limitations on many of the platforms we support in Cpp,
we decided simply returning strings of the JSON response data was the best course of action in our case.

**Comment by ItsANameToo** [comment]
I'm not sure whether we need the crypto lib for the models. We can just use primitive types and don't do any further checking; the models just serve to make the properties have their correct types (instead of `Any` and having to cast it to the right type yourself in case of Swift), but maybe I'm overlooking something so please elaborate if that's the case.

I know about the preference of Brian and I agree with him that it's better to let a dev decide for themselves how to use it. However, since Swift is a typed language, I also think that a lot of people will be happy if the client returns a model with the correct types that they can immediately use. However, maybe it would be better suited to make my own "model" extension library instead of integrating it with this client. Then people that want it can include that library to get the correct models, while the ones that don't need it / take care of it themselves can stick with the `Dictionary` it returns right now.

With C++ you have the additional constraint of the platforms on which it is used, I don't think we will have the same constraints with iOS / macOS. Most devices nowadays are pretty buffed with RAM and whatnot, and I don't expect people to develop programs that need to work on the oldest iPhones (like pre iPhone 3GS) since that would bring even more issues like outdated OSes.

Anyway, thanks for the insight in your choice regarding models with C++. I think I'll stick to the json / dictionary responses for this client too.

**Comment by sleepdefic1t** [comment]
Re models:
Basically,
In order to properly construct an address,
I feel we should also have to check that it is a valid address.

While a model is not a crypto protocol requiring a validation function,
I wonder if we’re not guaranteeing them a properly formed model that we can’t promise isn’t somehow corrupted.


Swift is certainly different than C++ with a lot less constraints,
and I like your template idea too.
Definitely understand where you’re coming from.
It really feels like you’re supposed to give them more here.

C++ will also likely do some sort of “client plugins” feature since we’ll be using IoT devices.
Similar to how core will have plugins.

Maybe we get some cross-wrapper standard going for things like Client return models, delegate scripts, URI/URL models, etc as well.
That could be a good spot for “experimental” or “extra”/optional goodies that don’t really fit the scope of a basic client.
Let me know what you think of that as well.

**Comment by ItsANameToo** [comment]
Standards would be nice for extensions. Maybe they could be added to docs.ark.io to give people guidelines on what they should include if they decide to start working on one.
